# Generated by Django 3.0.3 on 2020-06-13 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='<ul><li>YouTube: A channel identifier</li><li>last.fm: The name of a musical artist</li><li>Reddit: The name of a subreddit</li><li>Flickr: A tag for pictures</li><li>Goodreads: The name of a book author</li><li>Spotify: The name of a musical artist</li></ul>', max_length=64, verbose_name='key')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('source', models.CharField(choices=[('yt', 'YouTube'), ('lfm', 'last.fm'), ('rd', 'Reddit'), ('fl', 'Flickr'), ('gr', 'Goodreads'), ('sp', 'Spotify')], default='yt', max_length=32, verbose_name='source')),
                ('chosen', models.BooleanField(default=True, verbose_name='chosen')),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('picture', models.URLField(blank=True, default='', verbose_name='picture')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='miscosas.Feed', verbose_name='feed')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture')),
                ('theme', models.CharField(choices=[('lm', 'Light mode'), ('dm', 'Dark mode')], default='lm', max_length=2, verbose_name='theme')),
                ('font_size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=2, verbose_name='font size')),
                ('chosen_feeds', models.ManyToManyField(related_name='users', to='miscosas.Feed')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('content', models.CharField(max_length=256, verbose_name='content')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='miscosas.Item', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField(verbose_name='positive')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='miscosas.Item', verbose_name='item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
