# Generated by Django 3.0.3 on 2020-05-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
    ]
