# Generated by Django 3.0.3 on 2020-05-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0005_auto_20200518_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='feeds',
        ),
    ]
