# Generated by Django 3.0.3 on 2020-05-19 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0006_remove_profile_feeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='font_size',
            field=models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('LM', 'Light mode'), ('DM', 'Dark mode')], default='LM', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='miscosas.Item'),
        ),
    ]
