# Generated by Django 3.0.3 on 2020-05-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0007_auto_20200519_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
