# Generated by Django 3.0.3 on 2020-05-20 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0008_auto_20200519_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='chosen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='miscosas.Feed'),
        ),
    ]
