# Generated by Django 3.0.3 on 2020-05-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0010_auto_20200521_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='origin',
            new_name='source',
        ),
    ]
