# Generated by Django 3.0.3 on 2020-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0011_auto_20200524_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source',
            field=models.CharField(choices=[('yt', 'YouTube'), ('lfm', 'last.fm')], default='yt', max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('lm', 'Light mode'), ('dm', 'Dark mode')], default='lm', max_length=2),
        ),
    ]
