# Generated by Django 3.0.3 on 2020-06-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscosas', '0013_auto_20200606_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_feeds',
            field=models.ManyToManyField(related_name='users', to='miscosas.Feed'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='key',
            field=models.CharField(help_text='<ul><li>YouTube: A channel identifier</li><li>last.fm: The name of a musical artist</li><li>Reddit: The name of a subreddit</li><li>Flickr: A tag for pictures</li><li>Goodreads: The name of a book author</li><li>Spotify: The name of a musical artist</li></ul>', max_length=64, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='source',
            field=models.CharField(choices=[('yt', 'YouTube'), ('lfm', 'last.fm'), ('rd', 'Reddit'), ('fl', 'Flickr'), ('gr', 'Goodreads'), ('sp', 'Spotify')], default='yt', max_length=32, verbose_name='source'),
        ),
    ]
